const Menu = [
    {
        product_id: 1,
        product_name: "Magiee",
        product_image: "img",
        product_category: "Evening",
        product_description: "About Magiee",
        product_price: "14",
    },
    {
        product_id: 2,
        product_name: "Samosa",
        product_image: "samosaImage",
        product_category: "Breakfast",
        product_description: "Samosa Description",
        product_price: "15",
    },
    {
        product_id: 3,
        product_name: "Pizza",
        product_image: "pizzaImage",
        product_category: "Lunch",
        product_description: "Pizza Description",
        product_price: "20",
    },
    {
        product_id: 4,
        product_name: "Burger",
        product_image: "burgerImage",
        product_category: "Lunch",
        product_description: "Burger Description",
        product_price: "18",
    },
    {
        product_id: 5,
        product_name: "Coffee",
        product_image: "coffeeImage",
        product_category: "Beverages",
        product_description: "Coffee Description",
        product_price: "5",
    },
    {
        product_id: 6,
        product_name: "Tea",
        product_image: "teaImage",
        product_category: "Beverages",
        product_description: "Tea Description",
        product_price: "3",
    },
    {
        product_id: 7,
        product_name: "Pasta",
        product_image: "pastaImage",
        product_category: "Dinner",
        product_description: "Pasta Description",
        product_price: "22",
    },
    {
        product_id: 8,
        product_name: "Fries",
        product_image: "friesImage",
        product_category: "Dinner",
        product_description: "Fries Description",
        product_price: "10",
    },
    {
        product_id: 9,
        product_name: "Ice Cream",
        product_image: "iceCreamImage",
        product_category: "Dessert",
        product_description: "Ice Cream Description",
        product_price: "8",
    },
    {
        product_id: 10,
        product_name: "Cake",
        product_image: "cakeImage",
        product_category: "Dessert",
        product_description: "Cake Description",
        product_price: "25",
    }
    
]

export default Menu;